name: fitness-platform-adonis

services:
  postgres:
    image: postgres:17.4
    container_name: fitness-platform-adonis-postgres
    environment:
      POSTGRES_DB: fitness-platform-adonis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - fitness-platform-adonis_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:1.76.0
    container_name: fitness-platform-adonis-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # Jaeger UI
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    restart: unless-stopped

volumes:
  fitness-platform-adonis_postgres_data:
